Repository SWEatUNIPD/docs, pull requests merged in 2024-11, with the labels that each got.

#14 Correzione lettera candidatura
  candidatura/lettera_di_presentazione_candidatura.typ
  templates/template.typ
Labels: Lettera

#15 Verifica VE_2024-10-23_ver1.2.0
  candidatura/verbali/esterni/VE_2024-10-23_ver1.2.0.typ
Labels: Verbale

#21 Stesura VI_2024-11-10_ver1.0.0
  rtb/verbali/interni/VI_2024-11-10_ver1.0.0.typ
Labels: Verbale

#23 Redazione prima versione del glossario
  candidatura/valutazione_capitolati_ver1.2.1.typ
  candidatura/verbali/esterni/VE_2024-10-23_ver1.2.1.pdf
  candidatura/verbali/esterni/VE_2024-10-23_ver1.2.1.typ
  glossario_ver1.0.0.typ
  templates/template.typ
Labels: Glossario

#28 redazione VI_2024-11-13_ver1.0.0
  rtb/verbali/interni/VI_2024-11-13_ver1.0.0.typ
Labels: Verbale

#27 Redazione VE_2024-11-13_ver1.0.0
  rtb/verbali/esterni/VE_2024-11-13_ver1.0.0.typ
Labels: Verbale

#33 modifica VI_2024-11-13_ver1.0.1
  rtb/verbali/interni/VI_2024-11-13_ver1.0.1.typ
Labels: Verbale

#45 Creazione test del glossario
  .github/workflows/build.yml
  README.md
  glossario.json
  rtb/glossario_ver1.1.0.typ
  templates/template.typ
  test.js
Labels: Automazione

#40 redazione VE_2024-11-20_ver1.0.0
  .github/workflows/build.yml
  glossario.json
  rtb/glossario_ver2.0.0.typ
  rtb/verbali/esterni/VE_2024-11-20_ver1.0.0.typ
  templates/template.typ
Labels: Verbale

#46 Processi di supporto NdP
  glossario.json
  rtb/glossario_ver2.0.0.typ
  rtb/norme_di_progetto_ver1.0.0.typ
  rtb/norme_di_progetto_ver2.0.0.typ
Labels: NdP

#41 Processi primari ndp
  glossario.json
  rtb/glossario_ver3.1.0.typ
  rtb/norme_di_progetto_ver2.0.0.typ
  rtb/norme_di_progetto_ver3.0.0.typ
  rtb/verbali/interni/VI_2024-11-13_ver1.0.1.typ
Labels: NdP
