Repository SWEatUNIPD/docs, pull requests merged in 2024-12, with the labels that each got.

#62 Migliorie template
  .vscode/settings.json
  glossario.json
  rtb/analisi_dei_requisiti_ver0.2.0.typ
  rtb/glossario_ver0.7.0.typ
  rtb/piano_di_progetto_ver0.1.1.typ
  rtb/verbali/esterni/VE_2024-11-13_ver1.0.1.typ
  rtb/verbali/esterni/VE_2024-11-13_ver1.0.2.typ
  rtb/verbali/esterni/VE_2024-11-20_ver1.0.0.typ
  rtb/verbali/interni/VI_2024-11-10_ver1.0.0.typ
  rtb/verbali/interni/VI_2024-11-13_ver1.0.1.typ
  rtb/verbali/interni/VI_2024-11-20_ver1.0.0.typ
  templates/template.typ
  test.js
Labels: Template

#57 VE_2024-11-27
  glossario.json
  rtb/glossario_ver0.8.0.typ
  rtb/verbali/esterni/VE_2024-11-27_ver1.0.0.typ
Labels: Verbale

#58 VI_2024-11-28
  glossario.json
  rtb/verbali/interni/VI_2024-11-27_ver1.0.0.typ
Labels: Verbale

#64 VE_2024-12-04_ver1.0.0
  glossario.json
  rtb/glossario_ver0.7.1.typ
  rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
Labels: Verbale

#66 Prima stesura PdQ
  rtb/piano_di_qualifica_ver0.1.0.typ
Labels: PdQ

#67 Migliorie e aggiunta degli Use Case in AdR
  assets/use_cases/UC1-2-3.svg
  assets/use_cases/UC1.svg
  assets/use_cases/UC10.svg
  assets/use_cases/UC2.svg
  assets/use_cases/UC3.svg
  assets/use_cases/UC4.svg
  assets/use_cases/UC5-6.svg
  assets/use_cases/UC7-8.svg
  assets/use_cases/UC9.svg
  assets/use_cases/old/oldUC4.svg
  assets/use_cases/old/oldUC5.svg
  glossario.json
  rtb/analisi_dei_requisiti_ver0.2.0.typ
  rtb/analisi_dei_requisiti_ver0.3.0.typ
  rtb/glossario_ver0.10.0.typ
  rtb/glossario_ver0.8.0.typ
  templates/template.typ
Labels: AdR

#77 Creazione VI_2024-12-13_ver1.0.0.typ
  rtb/glossario_ver0.11.0.typ
  rtb/glossario_ver0.9.0.typ
  rtb/verbali/interni/VI_2024-12-13_ver1.0.0.typ
Labels: Verbale

#80 Pdp pianificazione terzo sprint
  rtb/piano_di_progetto_ver0.4.0.typ
Labels: PdP

#82 Adr nuovi use case
  assets/use_cases/dettagli storico.png
  assets/use_cases/display.png
  assets/use_cases/filtro.png
  assets/use_cases/grafici.png
  assets/use_cases/storico.png
  rtb/analisi_dei_requisiti_ver0.3.0.typ
  rtb/analisi_dei_requisiti_ver0.4.0.typ
Labels: AdR

#76 Processi organizzativi
  rtb/norme_di_progetto_ver0.6.0.typ
Labels: NdP

#93 stesura retrospettiva fine sprint 3
  rtb/piano_di_progetto_ver0.5.0.typ
Labels: PdP
