Repository SWEatUNIPD/docs, pull requests merged in 2025-01, with the labels that each got.

#94 Stesura VI 23-12-24
  glossario.json
  rtb/glossario_ver0.12.0.typ
  rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
Labels: Verbale

#95 redazione pianificazione sprint 4
  rtb/piano_di_progetto_ver0.6.0.typ
Labels: PdP

#97 Stesura del VE_2024-12-23
  rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
Labels: Verbale

#96 Sistemazione vecchi UC e aggiunta di nuovi
  assets/use_cases/UC1-2-3.svg
  assets/use_cases/UC1.png
  assets/use_cases/UC10.png
  assets/use_cases/UC10.svg
  assets/use_cases/UC11.png
  assets/use_cases/UC12.png
  assets/use_cases/UC13.png
  assets/use_cases/UC14.png
  assets/use_cases/UC15-16.png
  assets/use_cases/UC17.png
  assets/use_cases/UC18-19-20.png
  assets/use_cases/UC2-3-4-5.png
  assets/use_cases/UC21.png
  assets/use_cases/UC22.png
  assets/use_cases/UC23.png
  assets/use_cases/UC24.png
  assets/use_cases/UC25-26-27-28-29-30-31-32.png
  assets/use_cases/UC33-34-35-36.png
  assets/use_cases/UC37-38-39-40-41.png
  assets/use_cases/UC4.svg
  assets/use_cases/UC42-43-44-45.png
  assets/use_cases/UC46-47-48-49-50-51.png
  assets/use_cases/UC5-6.svg
  assets/use_cases/UC6-7.png
  assets/use_cases/UC7-8.svg
  assets/use_cases/UC8-9.png
  assets/use_cases/UC9.svg
  assets/use_cases/dettagli storico.png
  assets/use_cases/display.png
  assets/use_cases/filtro.png
  assets/use_cases/grafici.png
  assets/use_cases/old/oldUC4.svg
  assets/use_cases/old/oldUC5.svg
  assets/use_cases/storico.png
  rtb/analisi_dei_requisiti_ver0.4.0.typ
Labels: AdR

#110 Retrospettiva sprint 4
  rtb/piano_di_progetto_ver0.7.0.typ
Labels: PdP

#113 Requisiti
  assets/use_cases/UC1.png
  assets/use_cases/annuncio mancato marker.png
  assets/use_cases/annuncio marker.png
  assets/use_cases/autenticazione.png
  assets/use_cases/chiusure.png
  assets/use_cases/errori.png
  assets/use_cases/info poi marker.png
  assets/use_cases/mappa.png
  assets/use_cases/marker annuncio fallito.png
  assets/use_cases/marker annuncio.png
  assets/use_cases/notifica_annuncio_NON_generato.png
  assets/use_cases/notifica_annuncio_generato.png
  assets/use_cases/notifica_apertura_dettagli_annuncio.png
  assets/use_cases/notifica_chiusura.png
  assets/use_cases/percorso.png
  assets/use_cases/spostamento mappa.png
  assets/use_cases/zoom mappa.png
  rtb/analisi_dei_requisiti_ver0.5.0.typ
Labels: AdR

#100 71 ampliamento ndp
  rtb/norme_di_progetto_ver0.7.0.typ
Labels: NdP

#99 Metriche PdQ
  .vscode/settings.json
  rtb/piano_di_qualifica_ver0.1.0.typ
  rtb/piano_di_qualifica_ver0.2.0.typ
Labels: PdQ

#112 VI_2025-01-08
  rtb/verbali/interni/VI_2025-01-08_ver1.0.0.typ
Labels: Verbale

#111 VE_2025-01-08
  .vscode/settings.json
  rtb/verbali/esterni/VE_2025-01-08_ver1.0.0.typ
Labels: Verbale

#115 Pianificazione sprint 5
  assets/img/PdP/Periodo1.png
  assets/img/PdP/gantt_s2.png
  assets/img/PdP/gantt_s3.png
  assets/img/PdP/gantt_s4.png
  assets/img/unipd.png
  rtb/piano_di_progetto_ver0.8.0.typ
Labels: PdP

#98 Metriche di qualità del prodotto
  rtb/norme_di_progetto_ver0.8.0.typ
Labels: NdP

#117 VE_2025-01-15
  rtb/verbali/esterni/VE_2025-01-15_ver1.0.0.typ
Labels: Verbale

#114 Ultimazione casi d'uso
  assets/diagrams/activity-diagram.png
  assets/use_cases/UC1.png
  assets/use_cases/UC10.png
  assets/use_cases/UC11.png
  assets/use_cases/UC12.png
  assets/use_cases/UC13-14-15.png
  assets/use_cases/UC13.png
  assets/use_cases/UC14.png
  assets/use_cases/UC15-16.png
  assets/use_cases/UC16-17-18-19-20-21.png
  assets/use_cases/UC17.png
  assets/use_cases/UC18-19-20.png
  assets/use_cases/UC2-3-4-5.png
  assets/use_cases/UC21.png
  assets/use_cases/UC22-23-24-25.png
  assets/use_cases/UC22.png
  assets/use_cases/UC23.png
  assets/use_cases/UC24.png
  assets/use_cases/UC25-26-27-28-29-30-31-32.png
  assets/use_cases/UC26.png
  assets/use_cases/UC27.png
  assets/use_cases/UC28.png
  assets/use_cases/UC29-30-31.png
  assets/use_cases/UC32-33-34-35-36-37-38-39-40.png
  assets/use_cases/UC33-34-35-36.png
  assets/use_cases/UC37-38-39-40-41.png
  assets/use_cases/UC41-42-43-44-45-46-47.png
  assets/use_cases/UC42-43-44-45.png
  assets/use_cases/UC46-47-48-49-50-51.png
  assets/use_cases/UC48.png
  assets/use_cases/UC49.png
  assets/use_cases/UC50.png
  assets/use_cases/UC51.png
  assets/use_cases/UC52.png
  assets/use_cases/UC53-54-55-56.png
  assets/use_cases/UC57-58-59-60-61-62-63.png
  assets/use_cases/UC6-7.png
  assets/use_cases/UC8-9.png
  assets/use_cases/UC8.png
  assets/use_cases/UC9-10-11-12.png
  glossario.json
  rtb/analisi_dei_requisiti_ver0.5.0.typ
  rtb/analisi_dei_requisiti_ver0.6.0.typ
  rtb/glossario_ver0.14.0.typ
Labels: AdR

#121 Redazione dei requisiti di sistema
  assets/diagrams/activity-diagram.png
  assets/use_cases/UC16-17-18-19-20-21.png
  assets/use_cases/UC22-23-24-25.png
  assets/use_cases/UC26.png
  assets/use_cases/UC32-33-34-35-36-37-38-39-40.png
  assets/use_cases/UC32-33-34-35-36.png
  assets/use_cases/UC36-37-38-39-40.png
  assets/use_cases/UC41-42-43-44-45-46-47.png
  assets/use_cases/UC48.png
  assets/use_cases/UC57-58-59-60-61-62-63.png
  assets/use_cases/UC57-58-59.png
  assets/use_cases/UC59-60-61-62-63.png
  assets/use_cases/annuncio mancato marker.png
  assets/use_cases/annuncio marker.png
  assets/use_cases/autenticazione.png
  assets/use_cases/chiusure.png
  assets/use_cases/errori.png
  assets/use_cases/info poi marker.png
  assets/use_cases/mappa.png
  assets/use_cases/marker annuncio fallito.png
  assets/use_cases/marker annuncio.png
  assets/use_cases/notifica_annuncio_NON_generato.png
  assets/use_cases/notifica_annuncio_generato.png
  assets/use_cases/notifica_apertura_dettagli_annuncio.png
  assets/use_cases/notifica_chiusura.png
  assets/use_cases/percorso.png
  assets/use_cases/spostamento mappa.png
  assets/use_cases/zoom mappa.png
  glossario.json
  rtb/analisi_dei_requisiti_ver1.0.0.typ
  rtb/lettera_di_consegna_rtb.typ
Labels: AdR

#120 VE_2025-01-22
  rtb/verbali/esterni/VE_2025-01-22_ver1.0.0.typ
Labels: Verbale

#124 Glossario - Versione finale RTB
  glossario.json
  rtb/glossario_ver1.0.0.typ
  templates/template.typ
Labels: Glossario

#118 ultimazione ndp
  rtb/norme_di_progetto_ver1.0.0.typ
Labels: NdP

#126 Rilascio versione finale PdQ per RTB
  rtb/piano_di_qualifica_ver1.0.0.typ
  templates/template.typ
Labels: PdQ
