Repository SWEatUNIPD/docs, pull requests merged in 2025-03, with the labels that each got.

#153 retrospettiva sesto sprint
  pb/piano_di_progetto_ver1.2.0.typ
  rtb/piano_di_progetto_ver1.0.1.typ
Labels: PdP

#141 sistemazione adr
  assets/use_cases/UC1-2-3.png
  assets/use_cases/UC1.png
  assets/use_cases/UC10.png
  assets/use_cases/UC11-12-13-14.png
  assets/use_cases/UC13-14-15.png
  assets/use_cases/UC15-16-17.png
  assets/use_cases/UC16-17-18-19-20-21.png
  assets/use_cases/UC18-19-20-21-22-23.png
  assets/use_cases/UC2-3-4-5.png
  assets/use_cases/UC22-23-24-25.png
  assets/use_cases/UC24-25-26-27.png
  assets/use_cases/UC26.png
  assets/use_cases/UC27.png
  assets/use_cases/UC28.png
  assets/use_cases/UC29-30-31.png
  assets/use_cases/UC29.png
  assets/use_cases/UC30.png
  assets/use_cases/UC31-32-33.png
  assets/use_cases/UC32-33-34-35-36.png
  assets/use_cases/UC34-35-36-37-38.png
  assets/use_cases/UC36-37-38-39-40.png
  assets/use_cases/UC38-39-40-41-42.png
  assets/use_cases/UC4-5-6-7.png
  assets/use_cases/UC41-42-43-44-45-46-47.png
  assets/use_cases/UC43-44-45-46-47-48-49.png
  assets/use_cases/UC48.png
  assets/use_cases/UC49.png
  assets/use_cases/UC50.png
  assets/use_cases/UC51.png
  assets/use_cases/UC52.png
  assets/use_cases/UC53-54-55-56.png
  assets/use_cases/UC53.png
  assets/use_cases/UC54.png
  assets/use_cases/UC55-56-57-58.png
  assets/use_cases/UC57-58-59.png
  assets/use_cases/UC59-60-61-62-63-64.png
  assets/use_cases/UC59-60-61-62-63.png
  assets/use_cases/UC59-60-65-66-67.png
  assets/use_cases/UC6-7.png
  assets/use_cases/UC68.png
  assets/use_cases/UC8-9.png
  assets/use_cases/UC8.png
  assets/use_cases/UC9-10-11-12.png
  pb/analisi_dei_requisiti_ver1.1.0.typ
Labels: AdR

#152 stesura pianificazione sprint 7
  assets/img/PdP/gantt_s7.png
  pb/piano_di_progetto_ver1.3.0.typ
Labels: PdP

#160 Verbale interno 03-03-25
  glossario.json
  pb/verbali/interni/VI_2025-02-10.typ
  pb/verbali/interni/VI_2025-03-03.typ
Labels: Verbale

#149 redazione VE_2025-02-24
  glossario.json
  pb/glossario_ver1.0.1.typ
  pb/verbali/esterni/VE_2025-02-24.typ
Labels: Verbale

#150 Manuale Utente
  assets/img/Manuale/db-login.png
  assets/img/Manuale/grafana-login.png
  assets/img/Manuale/grafana-menu.png
  pb/manuale_utente_ver0.1.0.typ
Labels: MU

#165 Verbale esterno 03-03-2025
  glossario.json
  pb/glossario_ver1.2.0.typ
  pb/lettera_di_presentazione_rtb.typ
  pb/verbali/esterni/VE_2025-03-03.typ
Labels: Verbale

#161 Aggiornamento NdP
  pb/norme_di_progetto_ver1.2.0.typ
Labels: NdP

#163 definizione test di sistema nel pdq
  pb/analisi_dei_requisiti_ver1.1.0.typ
  pb/piano_di_qualifica_ver1.1.0.typ
Labels: PdQ

#175 Retrospettiva sprint 7
  pb/piano_di_progetto_ver1.4.0.typ
Labels: PdP

#176 Redazione Specifica Tecnica
  pb/specifica_tecnica_ver0.1.0.typ
Labels: ST

#174 redazione VI_2025-03-10
  pb/verbali/interni/VI_2025-03-10.typ
Labels: Verbale

#180 Pianificazione ottavo sprint
  assets/img/PdP/gantt_s8.png
  pb/piano_di_progetto_ver1.5.0.typ
Labels: PdP

#179 Stesura VE_2025-03-10
  pb/verbali/esterni/VE_2025-03-10.typ
Labels: Verbale

#188 Prima stesura VE
  pb/verbali/esterni/VE_2025-03-18.typ
Labels: Verbale

#194 VI_2025-03-20
  pb/verbali/interni/VI_2025-03-20.typ
Labels: Verbale

#185 Simulatore e design pattern ST
  assets/img/ST/simulator.svg
  pb/specifica_tecnica_ver0.1.0.typ
  pb/specifica_tecnica_ver0.2.0.typ
Labels: ST

#187 Test d'unità simulatore
  pb/piano_di_qualifica_ver1.3.0.typ
Labels: PdQ

#184 sezione database in specifiche tecniche
  assets/diagrams/ER-diagram.png
  glossario.json
  pb/glossario_ver1.4.0.typ
  pb/specifica_tecnica_ver0.3.0.typ
  pb/specifica_tecnica_ver0.4.0.typ
Labels: ST

#196 modifiche adr
  assets/use_cases/pb/UC38-39-40-41-42.png
  assets/use_cases/pb/UC38-39-40-41.png
  assets/use_cases/pb/UC42-43-44-45-46-47.png
  assets/use_cases/pb/UC43-44-45-46-47-48-49.png
  assets/use_cases/pb/UC48.png
  assets/use_cases/pb/UC49.png
  assets/use_cases/pb/UC50.png
  assets/use_cases/pb/UC51.png
  assets/use_cases/pb/UC52.png
  assets/use_cases/pb/UC53-54-55-56.png
  assets/use_cases/pb/UC53.png
  assets/use_cases/pb/UC54.png
  assets/use_cases/pb/UC55-56-57-58.png
  assets/use_cases/pb/UC57-58-59-60-61-62.png
  assets/use_cases/pb/UC57-58-63-64-65.png
  assets/use_cases/pb/UC59-60-61-62-63-64.png
  assets/use_cases/pb/UC59-60-65-66-67.png
  assets/use_cases/pb/UC66.png
  assets/use_cases/pb/UC68.png
  pb/analisi_dei_requisiti_ver1.2.0.typ
Labels: AdR

#198 Tabella requisiti funzionali specifica tecnica
  pb/specifica_tecnica_ver0.5.0.typ
Labels: ST

#201 Retrospettiva 8
  assets/img/PdP/gantt_s8.png
  pb/analisi_dei_requisiti_ver2.0.0.typ
  pb/piano_di_progetto_ver2.0.0.typ
Labels: PdP

#202 Test integrazione pdq
  pb/analisi_dei_requisiti_ver2.0.0.typ
  pb/norme_di_progetto_ver1.2.0.typ
  pb/piano_di_qualifica_ver1.5.0.typ
Labels: PdQ

#195 ultimazione manuale utente
  assets/img/Manuale/annuncio_marker_dettaglio.png
  assets/img/Manuale/annuncio_selezionato.png
  assets/img/Manuale/dettaglio-POI-click.png
  assets/img/Manuale/dettaglio_annuncio.png
  assets/img/Manuale/dettaglio_grafico.png
  assets/img/Manuale/grafana-geomap.png
  assets/img/Manuale/grafici.png
  assets/img/Manuale/grafici_menu_tendina.png
  assets/img/Manuale/lista_dashboards.png
  assets/img/Manuale/marker_annuncio_multipli.png
  assets/img/Manuale/sel_dashboards.png
  assets/img/Manuale/storico_annunci.png
  glossario.json
  pb/glossario_ver1.3.0.typ
  pb/manuale_utente_ver0.1.0.typ
  pb/manuale_utente_ver1.0.0.typ
Labels: MU
