Repository SWEatUNIPD/docs, pull requests merged in 2025-02, with the labels that each got.

#128 Modifiche al versionamento
  rtb/analisi_dei_requisiti_ver1.0.1.typ
  rtb/norme_di_progetto_ver1.0.1.typ
  rtb/piano_di_progetto_ver1.0.1.typ
  rtb/piano_di_qualifica_ver1.0.1.typ
Labels: NdP, AdR, PdP, PdQ

#136 Modifiche al glossario e al template
  pb/analisi_dei_requisiti_ver1.0.1.typ
  pb/glossario_ver1.0.1.typ
  pb/lettera_di_presentazione_rtb.typ
  pb/norme_di_progetto_ver1.0.1.typ
  pb/piano_di_progetto_ver1.0.1.typ
  pb/piano_di_qualifica_ver1.0.1.typ
  rtb/lettera_di_presentazione_rtb.typ
  templates/template.typ
Labels: Template, Glossario

#137 Sistemazione NdP
  pb/norme_di_progetto_ver1.1.0.typ
Labels: NdP

#138 Stesura verbale interno 10-02-25
  pb/verbali/esterni/.gitkeep
  pb/verbali/interni/VI_2025-02-10.typ
Labels: Verbale

#139 VE_2025-02-10
  .vscode/settings.json
  pb/verbali/esterni/VE_2025-02-10.typ
Labels: Verbale

#151 Stesura verbale interno 24/02/2025
  pb/verbali/interni/VI_2025-02-24.typ
Labels: Verbale
